name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: multiple command
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            export TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
            export SITE_DOMAIN=${{ secrets.SITE_DOMAIN }}
            export ADMIN_USER_ID=${{ secrets.ADMIN_USER_ID }}
            cd docryte
            git fetch && git pull
            go build -o docryte docryte
            pkill docryte || true
            nohup ./docryte > docryte.log 2>&1 &
